# Generated by Django 3.2.8 on 2021-10-16 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myinstagram', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='myimage',
            new_name='image',
        ),
    ]
